name: batripal

services:
  api:
    container_name: batripal-api
    command: bun run start:dev
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 6060:3000

  app:
    container_name: batripal-app
    command: bun run start
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 7070:3000
